---
- name: The ultimate playbook
  hosts: master
  become: yes
  tasks:
    - name: Update package lists
      apt: 
        update_cache: yes

    - name: Install Apache2 and other dependencies
      apt:
        name: 
          - apache2
          - libcgi-fast-perl
          - libapache2-mod-fcgid
          - build-essential
          - curl
          - mariadb-server
        state: present

    - name: Restart Apache2
      service:
        name: apache2
        state: restarted
